apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.app.name }}-secret
  labels:
    app: {{ .Values.app.name }}

data:
  POSTGRES_PASSWORD: {{ .Values.app.env.password | b64enc }}
  #POSTGRES_PASSWORD: cG9zdGdyZXM=
