apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.name }}-pvc
  namespace: {{ .Values.db.namespace }}
spec:
  accessModes:
    - {{ .Values.db.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.db.pvc.resources.requests.storage }}