apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: "{{ .Values.pv.capacity.storage }}"
  accessModes:
    - {{ .Values.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.pv.storageClassName }}
  hostPath:
    path: {{ .Values.pv.hostPath.path}}


