apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  hostPath:
    path: /tmp/data


