{{- if .Values.global.networkPolicy.create }}



apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-network-policy
  namespace: db
spec:
  podSelector:
    matchLabels:
      db: postgres
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: flask
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app
    ports:
    - protocol: TCP
      port: 5432
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: flask
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app

    ports:
    - protocol: TCP
      port: 5432

{{- end }}