apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
  labels:
    app: flask
spec:
  ## can change
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      ## can change
      nodePort: 30031