apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.db.namespace }}
  name: {{ .Values.db.name }}-service
  labels:
    db: {{ .Values.db.name }}

spec:
  type: {{ .Values.db.service.type }}
  selector:
    db: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}