apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap
  namespace: {{ .Values.app.namespace }}
  
  labels:
    app: {{ .Values.app.name }}
data:
  DB_NAME: {{ .Values.app.db.name }}
  POSTGRES_USER: {{ .Values.app.db.user }}
  DB_PORT: {{ .Values.app.db.port }}
  DB_HOST: {{ .Values.app.db.host }}
