apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.name }}-configmap
  namespace: {{ .Values.db.namespace}}
  labels:
    db: {{ .Values.db.name }}
data:
  POSTGRES_DB: {{ .Values.db.env.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.db.env.POSTGRES_USER }}