### This file is example made by ChatGPT


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-postgres-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/pogiship/flask-postgres-note-app-with-helm-and-argoCD'
    targetRevision: HEAD
    path: 'helm-charts/flask-postgres-app'
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
